OnlineExam.UI/Controllers/MangementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineExam.Application.Interfaces;
using OnlineExam.Core.Entities;
using OnlineExam.UI.Custom;
using OnlineExam.UI.Helper;
using OnlineExam.UI.Models;
using System.Reflection;

namespace OnlineExam.UI.Controllers;

[AdminAuth]
public class MangementController : Controller
{
    private readonly ILogger<MangementController> _logger;
    private readonly IUnitOfWork _unitOfWork;

    public MangementController(ILogger<MangementController> logger, IUnitOfWork unitOfWork)
    {
        _logger = logger;
        _unitOfWork = unitOfWork;
    }

    [HttpGet]
    public IActionResult CreateExam()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateExam(ExamViewModel model)
    {
        if (ModelState.IsValid)
        {
            Examination exam = new Examination
            {
                ExamTitle = model.ExamTitle,
                ExamDescription = model.ExamDescription,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                QuestionCount = model.QuestionCount,
                DurationInHours = model.DurationInHours
            };
            await _unitOfWork.Examinations.AddAsync(exam);
            _logger.LogInformation("Exam created Successfully.");
            ViewData["SuccessMessage"] = "Exam created successfully.";
            return RedirectToAction("AddQuestion", new { examId = exam.Id });
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> AddQuestion(Guid examId)
    {
        TempData["ExamId"] = examId;
        ViewBag.QuestionTypes = new SelectList(await _unitOfWork.QuestionTypes.GetAllAsync());
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddQuestion(QuestionViewModel model)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.QuestionTypes = new SelectList(await _unitOfWork.QuestionTypes.GetAllAsync());
            return View(model);
        }

        var question = new Question { QuestionText = model.QuestionText, QuestionTypeId = model.QuestionType, IsActive = true, ExamId = (Guid)TempData["ExamId"] };
        await _unitOfWork.Questions.AddAsync(question);
        _logger.LogInformation("Question created successfully.");
        ViewData["SuccessMessage"] = "Question created successfully.";
        if(question.QuestionTypeId== (int)QuestionTypeEnum.Essay || question.QuestionTypeId== (int)QuestionTypeEnum.Complete)
            return RedirectToAction("AddQuestion", new { examId = question.ExamId });
        else
            return RedirectToAction("AddChoice", new { examId = question.ExamId, questionId = question.Id });
    }

    [HttpGet]
    public async Task<IActionResult> AddChoice(Guid questionId, Guid examId)
    {
        TempData["QuestionId"] = questionId;
        ViewBag.ExamId = examId;
        return View();

    }

    [HttpPost]
    public async Task<IActionResult> AddChoice(Choice choice)
    {
        if (ModelState.IsValid)
        {
            await _unitOfWork.Choices.AddAsync(choice);
            var questionChoice = new QuestionChoices { ChoiceId = choice.Id, QuestionId = (Guid)TempData["QuestionId"] };
            await _unitOfWork.QuestionChoices.AddAsync( questionChoice);
            _logger.LogInformation("Choice created successfully.");
            ViewData["SuccessMessage"] = "Choice created successfully.";

            return RedirectToAction("AddChoice", new { questionId = questionChoice.QuestionId, examId = ViewBag.ExamId });
        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> BackToQuestions(Guid examId)
    {
        ViewBag.ExamId = examId;
        return RedirectToAction("AddQuestion", new { examId = (Guid)TempData["ExamId"] });
    }

}

OnlineExam.UI/Controllers/StudentProgressController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineExam.Application.Interfaces;
using OnlineExam.Core.Entities;
using OnlineExam.UI.Custom;
using OnlineExam.UI.Models;

namespace OnlineExam.UI.Controllers;

[StudentAuth]
public class StudentProgressController : Controller
{
    private readonly ILogger<StudentProgressController> _logger;
    private readonly IUnitOfWork _unitOfWork;

    public StudentProgressController(ILogger<StudentProgressController> logger, IUnitOfWork unitOfWork)
    {
        _logger = logger;
        _unitOfWork = unitOfWork;
    }

    [HttpGet]
    public async Task<IActionResult> GetProgressDetails(Guid ExamId)
    {
        var userId = Guid.TryParse(HttpContext.Request.Cookies["UserId"], out var parsedUserId) ? parsedUserId : default;
        var user = await _unitOfWork.Users.GetByIdAsync(userId);
        var exam = await _unitOfWork.Examinations.GetByIdAsync(ExamId);
        var totalScore = _unitOfWork.Questions.GetByExamIdAsync(ExamId).Result.Sum(q => q.Points);
        var progress = await _unitOfWork.StudentProgress.GetExamProgressByUserId(userId, ExamId);

        var progressVM = new StudentProgressVM
        {
            ExamId = exam.Id,
            ExamTitle = exam.ExamTitle,
            StudentScore = progress.Score,
            Timestamp = progress.Timestamp,
            UserName = user.FirstName + " " + user.LastName,
            TotalScore = totalScore,
        };
        return View(progressVM);
    }

    [HttpGet]
    public async Task<IActionResult> GetAllProgressList()
    {
        var userId = Guid.TryParse(HttpContext.Request.Cookies["UserId"], out var parsedUserId) ? parsedUserId : default;
        var user = await _unitOfWork.Users.GetByIdAsync(userId);
        var exams = (await _unitOfWork.Answers.GetAllAsync()).Select(a => a.ExamId).ToList()
            .Select(async item => await _unitOfWork.Examinations.GetByIdAsync(item))
            .Select(task => task.Result)
            .ToList();

        var progressList = new List<StudentProgressVM>();

        foreach (var exam in exams)
        {
            var totalScore = (await _unitOfWork.Questions.GetByExamIdAsync(exam.Id)).Sum(q => q.Points);
            var progress = await _unitOfWork.StudentProgress.GetExamProgressByUserId(userId, exam.Id);

            var progressVM = new StudentProgressVM
            {
                ExamId = exam.Id,
                ExamTitle = exam.ExamTitle,
                StudentScore = progress.Score,
                Timestamp = progress.Timestamp,
                UserName = $"{user.FirstName} {user.LastName}",
                TotalScore = totalScore
            };

            progressList.Add(progressVM);
        }

        return View(progressList);
    }
}

OnlineExam.UI/Views/Shared/_Layout.cshtml
@{
    string roleId = Context.Request.Cookies["RoleId"];
string userId = Context.Request.Cookies["UserId"];
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OnlineExam | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineExam.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineExam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @switch(roleId)
                    {
                        case "1":
                            <li class="nav-item">
                                    <a class="nav-link" asp-controller="Mangement" asp-action="CreateExam">Add Exam</a>
                                </li>
                        break;
                        case "2":
                            <li class="nav-item">
                                    <a class="nav-link" asp-controller="Answer" asp-action="ListExams">Answer Exam</a>
                                </li>
                            <li class="nav-item">
                                    <a class="nav-link" asp-controller="StudentProgress" asp-action="GetAllProgressList">My Exams Progress</a>
                            </li>

                        break;
                    }
                        @if (userId!=null)
                    {
                        <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023  <a href="#">Online Exam</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>